<a href="https://colab.research.google.com/github/cpython-projects/da_27_07_2026/blob/main/lesson_19_hw.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Легенда

**[Students Performance in Exams](https://github.com/cpython-projects/python_da_06_11_25/blob/main/StudentsPerformance.csv)**

Датасет містить інформацію про результати учнів та деякі соціальні характеристики, які можуть впливати на успішність.

## Опис змінних

* **gender** — стать учня
* **race/ethnicity** — етнічна група учня
* **parental level of education** — рівень освіти батьків
* **lunch** — тип харчування в школі
* **test preparation course** — чи проходив учень підготовчий курс перед іспитом
* **math score** — бал за іспит з математики
* **reading score** — бал за іспит з читання
* **writing score** — бал за іспит з письма

In [1]:
import pandas as pd
import plotly.express as px

df = pd.read_csv('https://raw.githubusercontent.com/cpython-projects/python_da_06_11_25/refs/heads/main/StudentsPerformance.csv')
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

# Task 1  

> З якими результатами з математики учні стикаються найчастіше:
> чи більше учнів отримують середні бали, чи результати зосереджені біля мінімуму або максимуму?

In [3]:
fig = px.histogram(df, x='math score', nbins=25, title='Розподіл балів з математики')
fig.add_vline(x=df['math score'].mean(), line_color='red', line_dash='dash')
fig.show()

# Task 2  

> Порівняти середній бал з читання для учнів, які проходили підготовчий курс перед іспитом, і тих, хто його не проходив.
> Яка група виглядає успішнішою?

In [4]:
df.columns.to_list()

['gender',
 'race/ethnicity',
 'parental level of education',
 'lunch',
 'test preparation course',
 'math score',
 'reading score',
 'writing score']

In [6]:
df['test preparation course'].unique()

array(['none', 'completed'], dtype=object)

In [7]:
df.groupby('test preparation course')['reading score'].mean()

test preparation course
completed    73.893855
none         66.534268
Name: reading score, dtype: float64

In [5]:
fig = px.bar(df,
             x='test preparation course',
             y='reading score',
             color='test preparation course',
             title='Бал з читання (підготовку пройдено / не пройдено)'
             )
fig.show()

In [9]:
fig = px.box(df,
             x='test preparation course',
             y='reading score',
             color='test preparation course',
             title='Бал з читання (підготовку пройдено / не пройдено)'
             )
fig.update_traces(boxmean=True)
fig.show()

# Task 3  

> Як відрізняється розподіл балів з письма між учнями з різним рівнем освіти батьків?
> У яких групах результати більш стабільні, а де — сильніше коливаються?

In [10]:
fig = px.box(df,
             x='parental level of education',
             y='writing score',
             color='parental level of education'
             )
fig.update_traces(boxmean=True)
fig.show()

# Task 4  

> Як виглядає розташування учнів на площині
> «бал з читання — бал з письма»?
> Чи є учні з нетиповими поєднаннями результатів?

In [12]:
fig = px.scatter(df, x='writing score', y='reading score').show()